'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { StatusBadge } from '@/components/status-badge';
import { apiFetch, ApiError } from '@/lib/api';
import { dateTime, money } from '@/lib/format';
import type { Order, OrderStatus, Paginated, Product } from '@/lib/types';
import { useAuth } from '@/lib/auth-context';

type Dashboard={customers:number;activeProducts:number;lowStock:number;orders:number;revenueInCents:number;recentOrders:Order[]};
type Customer={id:string;name:string;email:string;isActive:boolean;createdAt:string;_count:{orders:number}};
type Movement={id:string;type:string;quantity:number;reason:string;createdAt:string;product:{sku:string;name:string};order?:{number:string}};
type Tab='dashboard'|'products'|'orders'|'customers'|'inventory';

const nextStatuses:Record<OrderStatus,OrderStatus[]>={PENDING:['PAID','CANCELLED'],PAID:['PROCESSING','CANCELLED'],PROCESSING:['SHIPPED'],SHIPPED:['DELIVERED'],DELIVERED:[],CANCELLED:[]};

export default function AdminPage(){
  const {user,loading:authLoading}=useAuth();const router=useRouter();const [tab,setTab]=useState<Tab>('dashboard');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [success,setSuccess]=useState('');
  const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [products,setProducts]=useState<Product[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [movements,setMovements]=useState<Movement[]>([]);
  const [form,setForm]=useState({sku:'',name:'',description:'',imageUrl:'',price:'',stock:'0'});

  async function load(){setLoading(true);setError('');try{const [d,p,o,c,m]=await Promise.all([apiFetch<Dashboard>('/admin/dashboard'),apiFetch<Paginated<Product>>('/admin/products?includeInactive=true&limit=100'),apiFetch<Paginated<Order>>('/admin/orders?limit=100'),apiFetch<Paginated<Customer>>('/admin/customers?limit=100'),apiFetch<Paginated<Movement>>('/admin/inventory/movements?limit=100')]);setDashboard(d);setProducts(p.items);setOrders(o.items);setCustomers(c.items);setMovements(m.items)}catch(e){setError(e instanceof ApiError?e.message:'Falha ao carregar a administração.')}finally{setLoading(false)}}
  useEffect(()=>{if(!authLoading){if(!user)router.push('/login');else if(user.role!=='ADMIN')router.push('/catalog');else void load()}},[authLoading,user]);
  function notice(message:string){setSuccess(message);setTimeout(()=>setSuccess(''),3500)}
  async function createProduct(e:FormEvent){e.preventDefault();setError('');try{await apiFetch('/products',{method:'POST',body:JSON.stringify({sku:form.sku,name:form.name,description:form.description||undefined,imageUrl:form.imageUrl||undefined,priceInCents:Math.round(Number(form.price)*100),stock:Number(form.stock),active:true})});setForm({sku:'',name:'',description:'',imageUrl:'',price:'',stock:'0'});notice('Produto criado com sucesso.');await load()}catch(err){setError(err instanceof ApiError?err.message:'Falha ao criar produto.')}}
  async function adjust(product:Product){const raw=window.prompt(`Ajuste para ${product.name}. Use positivo para entrada e negativo para saída:`,`1`);if(raw===null)return;const delta=Number(raw);if(!Number.isInteger(delta)||delta===0){setError('Informe um número inteiro diferente de zero.');return}const reason=window.prompt('Motivo do ajuste:','Ajuste administrativo');if(!reason)return;try{await apiFetch(`/products/${product.id}/stock`,{method:'PATCH',body:JSON.stringify({delta,reason})});notice('Estoque atualizado.');await load()}catch(e){setError(e instanceof ApiError?e.message:'Falha ao ajustar estoque.')}}
  async function edit(product:Product){const name=window.prompt('Nome do produto:',product.name);if(!name)return;const description=window.prompt('Descrição:',product.description||'');if(description===null)return;const price=window.prompt('Preço em reais:',String(product.priceInCents/100));if(price===null)return;const priceInCents=Math.round(Number(price.replace(',','.'))*100);if(!Number.isInteger(priceInCents)||priceInCents<1){setError('Preço inválido.');return}try{await apiFetch(`/products/${product.id}`,{method:'PATCH',body:JSON.stringify({name,description,priceInCents})});notice('Produto atualizado.');await load()}catch(e){setError(e instanceof ApiError?e.message:'Falha ao editar produto.')}}
  async function remove(product:Product){if(!window.confirm(`Desativar ${product.name}?`))return;try{await apiFetch(`/products/${product.id}`,{method:'DELETE'});notice('Produto desativado.');await load()}catch(e){setError(e instanceof ApiError?e.message:'Falha ao desativar.')}}
  async function status(order:Order,next:OrderStatus){try{await apiFetch(`/admin/orders/${order.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});notice('Status atualizado.');await load()}catch(e){setError(e instanceof ApiError?e.message:'Transição não permitida.')}}
  if(authLoading||loading)return <div className="loading">Carregando painel administrativo...</div>;
  return <section className="page"><div className="shell"><div className="page-head"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Painel operacional</h1><p>Gestão completa de pedidos, produtos, clientes e estoque.</p></div><button className="button ghost" onClick={()=>load()}>Atualizar dados</button></div>{error&&<div className="form-error" style={{marginBottom:14}}>{error}</div>}{success&&<div className="form-success" style={{marginBottom:14}}>{success}</div>}
  <div className="admin-tabs">{([['dashboard','Visão geral'],['products','Produtos'],['orders','Pedidos'],['customers','Clientes'],['inventory','Estoque']] as [Tab,string][]).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
  {tab==='dashboard'&&dashboard&&<><div className="stats-grid"><div className="stat"><small>Receita processada</small><strong>{money(dashboard.revenueInCents)}</strong></div><div className="stat"><small>Pedidos</small><strong>{dashboard.orders}</strong></div><div className="stat"><small>Clientes</small><strong>{dashboard.customers}</strong></div><div className="stat"><small>Produtos ativos</small><strong>{dashboard.activeProducts}</strong></div><div className="stat"><small>Estoque baixo</small><strong>{dashboard.lowStock}</strong></div></div><div className="panel"><h2>Pedidos recentes</h2><OrderTable orders={dashboard.recentOrders} onStatus={status}/></div></>}
  {tab==='products'&&<div className="modal-grid"><form className="panel form-grid" onSubmit={createProduct}><h2>Novo produto</h2><div className="field"><label>SKU</label><input className="input" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} required/></div><div className="field"><label>Nome</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div className="field"><label>Descrição</label><textarea className="textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="field"><label>URL da imagem</label><input className="input" type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></div><div className="form-grid two"><div className="field"><label>Preço em reais</label><input className="input" type="number" step="0.01" min="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/></div><div className="field"><label>Estoque inicial</label><input className="input" type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} required/></div></div><button className="button primary">Cadastrar produto</button></form><div className="panel"><h2>Produtos cadastrados</h2><div className="table-wrap"><table className="table"><thead><tr><th>SKU</th><th>Produto</th><th>Preço</th><th>Estoque</th><th>Status</th><th>Ações</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.sku}</td><td><strong>{p.name}</strong></td><td>{money(p.priceInCents)}</td><td>{p.stock}</td><td>{p.active?'Ativo':'Inativo'}</td><td><div className="inline-actions"><button className="button ghost small" onClick={()=>edit(p)}>Editar</button><button className="button secondary small" onClick={()=>adjust(p)}>Estoque</button>{p.active&&<button className="button danger small" onClick={()=>remove(p)}>Desativar</button>}</div></td></tr>)}</tbody></table></div></div></div>}
  {tab==='orders'&&<div className="panel"><h2>Todos os pedidos</h2><OrderTable orders={orders} onStatus={status}/></div>}
  {tab==='customers'&&<div className="panel"><h2>Clientes</h2><div className="table-wrap"><table className="table"><thead><tr><th>Nome</th><th>E-mail</th><th>Pedidos</th><th>Cadastro</th><th>Status</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email}</td><td>{c._count.orders}</td><td>{dateTime(c.createdAt)}</td><td>{c.isActive?'Ativo':'Desativado'}</td></tr>)}</tbody></table></div></div>}
  {tab==='inventory'&&<div className="panel"><h2>Movimentações de estoque</h2><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Produto</th><th>Tipo</th><th>Quantidade</th><th>Motivo</th><th>Pedido</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{dateTime(m.createdAt)}</td><td><strong>{m.product.name}</strong><br/><small>{m.product.sku}</small></td><td>{m.type}</td><td style={{fontWeight:800,color:m.quantity>=0?'var(--accent)':'var(--danger)'}}>{m.quantity>0?'+':''}{m.quantity}</td><td>{m.reason}</td><td>{m.order?.number||'—'}</td></tr>)}</tbody></table></div></div>}
  </div></section>
}

function OrderTable({orders,onStatus}:{orders:Order[];onStatus:(order:Order,next:OrderStatus)=>void}){return <div className="table-wrap"><table className="table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Total</th><th>Status</th><th>Próxima ação</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><strong>{order.number}</strong></td><td>{order.user?.name||'Cliente'}<br/><small>{order.user?.email}</small></td><td>{dateTime(order.createdAt)}</td><td>{money(order.totalInCents)}</td><td><StatusBadge status={order.status}/></td><td>{nextStatuses[order.status].length?<select className="select" defaultValue="" onChange={e=>{if(e.target.value)onStatus(order,e.target.value as OrderStatus);e.currentTarget.value=''}}><option value="">Alterar...</option>{nextStatuses[order.status].map(value=><option key={value} value={value}>{value}</option>)}</select>:<span>Finalizado</span>}</td></tr>)}</tbody></table></div>}
